{
 "title": "Spring Application",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Count By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "60eb990a", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "Hybris" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "GET /dice",
        "GET /message",
        "GET /inventory/"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"Hybris\" && (name=\"GET /dice\" || name=\"GET /message\" || name=\"GET /inventory/\")} | count_over_time() by (name)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Generated Message Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{\"text-message.histogram_count\"}",
     "legendFormat": "{{text.message}}"
    }
   ]
  },
  {
   "title": "Do Work Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{\"do-work.gauge.response.time_milliseconds\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}